### ISSUE TITLE
[Docs] Link to Sylvain Julé's colour picker is broken

### ISSUE THREAD

**Issue by iocouto** [hananils/kirby-colors#17]
I believe the colour picker that the docs mean to refer to in the "Alternatives" section is probably this one:

https://github.com/sylvainjule/kirby-color-palette

**Comment by nilshoerrmann** [comment]
Thanks for the info, I didn't noticed the broken link before. Sylvain actually had a fork of Tim's plugin with changes that must have been merged into the main repo in the meantime. The Color Palette plugin has a different purpose.
