### ISSUE TITLE
Add compatibility with Kirbys plugin update check

### ISSUE THREAD

**Issue by flokuek** [hananils/kirby-colors#32]
Kirby 3.8 introduced a new update check for Kirby and plugins. Currently the plugin directory is set to `hananils/colors` on Kirbys website [https://getkirby.com/plugins/<vendor>/<plugin>](https://getkirby.com/plugins/hananils/colors) but the plugin name in `index.php` is set to `hananils/kirby-colors` hence the panel fails to do the update check.

This should be a quick change but would be nice to have :) Thanks!

**Comment by tobimori** [comment]
#31
