### ISSUE TITLE
fix readme or name of package in packagist

### ISSUE THREAD

**Issue by bnomei** [hananils/kirby-colors#7]
at packagist you omitted `kirby-` in the packagename. fix that there or adjust the readme.

https://packagist.org/packages/hananils/

**Comment by bnomei** [comment]
since its the same as in the composer.json you should fix it there as well.
```json
{
    "name": "hananils/colors",
```

**Comment by nilshoerrmann** [comment]
There is no such thing as a rename feature on Packagist, is there?

**Comment by bnomei** [comment]
no. i do not think so. 
- remove from packagist
- you need to change the composer file. commit it. 
- create a release
- add repo to packagist again

**Comment by nilshoerrmann** [comment]
I love modern web development … 
Thanks for your help!

**Comment by nilshoerrmann** [comment]
Is removing the same as abandoning? Sorry, I'm not used to how Packagist works.

**Comment by bnomei** [comment]
you are right 😅 . there is no remove. just try to update the composer file and release and try the "update" button at packagist.

**Comment by nilshoerrmann** [comment]
Here we go: https://packagist.org/packages/hananils/kirby-colors
