### ISSUE TITLE
Error when trying to enter HSL values

### ISSUE THREAD

**Issue by hariom147** [hananils/kirby-colors#9]
When trying to enter a HSL value, I get this error:

> undefined is not an object (evaluating 'r[t].value')

When reloading the panel page, it works (maybe becaus HSL is already selected from the dropdown menu in this case).

Also, when deleting HSL value in first field, it jumps back to HEX.

**Comment by nilshoerrmann** [comment]
Thanks for your report. I will have a look at it next week.
